# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv pip install "flake8>=6.0.0,<7.0.0" pytest
        uv pip install -e .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 fcg/ --count --select=E9,F63,F7,F82 --show-source --statistics --jobs 1
        # exit-zero treats all errors as warnings. Ignore line too long (E501)
        uv run flake8 fcg/ --count --exit-zero --max-complexity=10 --ignore=E501 --statistics --jobs 1
    - name: Test with pytest
      run: |
        uv run pytest -m "not llm"
